name: Bug Report
description: Report a bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out a bug report! We ask that you search all the issues to avoid a duplicate bug report. If one exists, please reply with as much information as possible.
        Before reporting a bug here, please make sure you are on the latest supported version. 

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed/actual behavior
      description: What you actually saw.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a screenshot, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Version
      description: Please provide the version of the mod you're running. This can be found in the file name of the mod jar.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other information that may be helpful below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false